name: Test with pytest

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@839076380bea7d7e5115ed87d57d4f8606bda938
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - run: uv sync --group test
      - run: uv run pytest
